/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BotControlPanel.java
 *
 * Created on Feb 13, 2010, 1:00:58 AM
 */

package automenta.netention.swingui.botpanel;

import automenta.netention.swingui.html.HTMLCrawlPanel;
import automenta.netention.swingui.util.SwingWindow;
import javax.swing.JScrollPane;

/**
 *
 * @author seh
 */
public class BotControlPanel extends javax.swing.JPanel {
    private final MatchBotPanel botPanel;

    public BotControlPanel(MatchBotPanel botPanel) {
        super();
        this.botPanel = botPanel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        inputField = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();
        summarizeButton = new javax.swing.JButton();
        showConcepts = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        add(inputField, gridBagConstraints);

        filterButton.setText("Spider...");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });
        add(filterButton, new java.awt.GridBagConstraints());

        summarizeButton.setText("Summarize");
        add(summarizeButton, new java.awt.GridBagConstraints());

        showConcepts.setText("Concepts...");
        showConcepts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showConceptsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(showConcepts, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
        botPanel.addSource(inputField.getText());
        inputField.setText("");
    }//GEN-LAST:event_inputFieldActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        // TODO add your handling code here:
        new SwingWindow(
        new JScrollPane(new HTMLCrawlPanel(botPanel.getSelf()) {
            @Override protected void finished() {
            }
        }), 400, 400, false);
    }//GEN-LAST:event_filterButtonActionPerformed

    private void showConceptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showConceptsActionPerformed
        // TODO add your handling code here:
        botPanel.updateConcepts();
    }//GEN-LAST:event_showConceptsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filterButton;
    private javax.swing.JTextField inputField;
    private javax.swing.JButton showConcepts;
    private javax.swing.JButton summarizeButton;
    // End of variables declaration//GEN-END:variables

}
